import type { Metadata } from 'next'
import './globals.css'
import tippy from 'tippy.js';
import 'tippy.js/dist/tippy.css';
import { inter, ibmPlexMono } from '@/app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${ibmPlexMono.variable} ${inter.className}`}>{children}</body>
    </html>
  )
}
